import { BlockDTO } from "../socket-client.provider";

export interface IKvp {
	key: string;
	value: any;
}

export interface handleNewBlock {
	(block: BlockDTO): Promise<void>;
}

export interface IContractingTime {
	__time__: [number, number, number, number, number, number];
}

export type StakingType =
	| "staking_simple"
	| "staking_smart_epoch"
	| "staking_smart_epoch_compounding_timeramp"
	| "liquidity_mining_smart_epoch"
	| "staking_smart_epoch_compounding"

export interface ITimeRampValue {
	lower: number;
	upper: number;
	multiplier: any; //{ __fixed__: string } | number;
}

// Generated by https://quicktype.io

export interface EpochResponse {
	value: Value;
}

export interface Value {
	amt_per_hr: any;
	staked: Staked;
	time: IContractingTime;
}

export interface Staked {
	__fixed__: string;
}
